export default {
  API_URL: "http://localhost:3000/api",
  SOCKET_URL: "http://localhost:3000",
  IMAGES_PATH: "/assets/images",
  CARDS: {
    COLORS: ["red", "blue", "green", "yellow"],
    SPECIALS: ["skip", "reverse", "plus-2"],
    NUMBERS: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    ALL: [
      "red-skip",
      "red-reverse",
      "red-plus-2",
      "red-1",
      "red-2",
      "red-3",
      "red-4",
      "red-5",
      "red-6",
      "red-7",
      "red-8",
      "red-9",
      "blue-skip",
      "blue-reverse",
      "blue-plus-2",
      "blue-1",
      "blue-2",
      "blue-3",
      "blue-4",
      "blue-5",
      "blue-6",
      "blue-7",
      "blue-8",
      "blue-9",
      "green-skip",
      "green-reverse",
      "green-plus-2",
      "green-1",
      "green-2",
      "green-3",
      "green-4",
      "green-5",
      "green-6",
      "green-7",
      "green-8",
      "green-9",
      "yellow-skip",
      "yellow-reverse",
      "yellow-plus-2",
      "yellow-1",
      "yellow-2",
      "yellow-3",
      "yellow-4",
      "yellow-5",
      "yellow-6",
      "yellow-7",
      "yellow-8",
      "yellow-9",
      "wild",
      "wild-plus-4",
    ],
  },
  CARD_BACK_PATH: "assets/images/cards/card-back.png",
};
